# Generated by Django 2.1.7 on 2019-04-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('description', models.TextField(blank=True)),
                ('working_from_hour', models.TimeField(blank=True, null=True)),
                ('working_to_hour', models.TimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='null', upload_to='images')),
                ('website', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='restaurants.Restaurant'),
        ),
    ]
